### ISSUE TITLE
Socket timeout

### ISSUE THREAD

**Issue by 4lloyd** [b10m/ziggo_mediabox_xl#1]
* Ziggo Mediabox XL version: unknown
* Python version: 3.6.6
* Operating System: Ubuntu 18.04

### Description

To be clear, I can connect to the mediabox with this package.

I'm trying to change the way the device is added in Home Assistant when the mediabox is in eco mode (so completely turned off), see: home-assistant/home-assistant#17990. The problem for me at the moment is that the socket connection doesn't timeout fast enough / at all. That gives problems with Home Assistant, because it expects to get an update within 10 seconds. Is it possible to add a timeout to the socket connections? Of maybe make this available "on the outside" so it can be configured?

If you don't have time for this than I can add it myself if you want.

### What I Did

Try to find a way around this problem, but I think adding the timeout is the best thing to do.

The warning from Home Assistant:
```
2018-11-02 22:04:05 WARNING (MainThread) [homeassistant.components.media_player] Updating ziggo_mediabox_xl media_player took longer than the scheduled update interval 0:00:10
```

**Comment by b10m** [comment]
Timeouts make sense here. In a2cab3f I set a default of 5 seconds (should be enough) and an option to configure it (10 seconds in this example):
```python
box = ZiggoMediaboxXL('192.168.1.2', 10)
``` 
Does that help, or is more needed?

**Comment by 4lloyd** [comment]
That helps for sure. Also very fast, thanks!

Maybe for completeness also add the timeout to the send_keys function.

**Comment by b10m** [comment]
Thought about it, but one would usually only send keys if a connection has been tested. But there's no good reason to _not_ have a time out there, so I'll add it and release a new version.

Will do patch anything home assistant related (if needed) ?

**Comment by b10m** [comment]
Version 1.1.0 released: https://pypi.org/project/ziggo-mediabox-xl/
